# Generated by Django 5.1.6 on 2025-03-11 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='article_category',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Article Categories'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='created_date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updated_date',
            new_name='updated_on',
        ),
        migrations.AddField(
            model_name='article_category',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
